# Generated by Django 3.2.7 on 2021-09-17 04:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_borrowed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrowed_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='borrowing_duration',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='borrowed',
            field=models.BooleanField(default=False, verbose_name='borrow'),
        ),
    ]
