# Generated by Django 3.2.7 on 2021-09-17 04:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210917_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrowed_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
