# Generated by Django 3.2.7 on 2021-09-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_borrowed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrowed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
