# Generated by Django 3.2.7 on 2021-09-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_borrowed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrowed_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='borrowing_duration',
            field=models.IntegerField(null=True),
        ),
    ]
