# Generated by Django 3.2.7 on 2021-09-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20210917_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrowing_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
