# Generated by Django 3.2.7 on 2021-09-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_borrowing_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='default_book.jpg', upload_to='book_covers'),
        ),
    ]
