# Generated by Django 3.2.7 on 2021-09-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_url',
            field=models.FileField(null=True, upload_to='books'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='books.Category'),
        ),
    ]
