# Generated by Django 3.2.7 on 2021-09-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210919_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='spoiled',
            field=models.BooleanField(default=False),
        ),
    ]
